---
title: "Criteria"
---
Below lists the criteria for the three different members of the OPA fellowship program.  


### Participants
- Have completed a Ph.D. in a social science or humanities field. 
- Passionate and ready to learn about how to share your skills and knowledge openly in support of the open web and a healthy internet (no prior experience necessary).
- Commitment to completing an open project. 
- Available to commit at least 3 hours per week for 8 weeks for attending weekly online meetings and completing open leadership assignments.
- Willingness to listen, support others and share resources as well as to abide by the Code of Conduct.  

### Mentors
- Have a PhD. 
- Familiar with the academic mindset and the challenges of leaving academia. 
- Supportive of the open web and a healthy internet.  
- Have spent two or more years working outside of academia. 
- Commitment to spending 2 - 3 hours per month mentoring a person leaving academia. 
- Willingness to listen, support others and share resources as well as to abide by the Code of Conduct.
 
### Experts 
- Have a PhD or have worked closely with PhDs or within an academic system. 
- Familiar with the academic mindset and the challenges of leaving academia. 
- Supportive of the open web and a healthy internet.
- Willing to be contacted for informational interviews by people within the OPA program. 
- Willingness to listen, support others and share resources as well as to abide by the Code of Conduct  

*Questions? Please ask them!* 

