---
title: "04-Networking"
output: html_document
---

# Networking {-}

- How can we make more connections to people outside of academia?
- But I'm an introvert/hate being skeezy/don't want to bug people. 
- What is an informational interview for?


## Informational Interviews {-}
Informational interviews are an incredibly important tool. Once you get the hang of them, they can be very helpful. 

I think there are a few myths about informational interviewing 

### Myth #1 - They're just for getting a job. {-}
You won't likely get a job from an informational interview. Take the idea of getting a job off the table. This is  not a job interview.  

Focus instead on people whose work seems interesting and who you'd like to know more about. 

You can absolutely do informational interviewing when you already have a job and just want to make connections and meet new people who do interesting things.


### Myth #2 - Info interviews are only helpful for the person who is asking to talk to the person with the cool job. {-}

Busy, interesting people with cool jobs know the importance of networking, but it can be hard to fit it into their life. If you make it easy for them to meet you, you are helping them make connections and talk to new people. 

You're inviting them into YOUR growing network and you might also know information they don't know. You also might tell them something they've never heard before. That's worthwhile.  


### Myth # 3 - You have to do a lot of homework before doing an informational interview {-}
You certainly can do homework and read up on the person and their work beforehand, it's nice to do. 

But it's also ok to walk into the conversation being genuinely curious about what they do and how they got there. 

### Myth #4 - I have to do all the work to find people who are good to do an informational interview with. {-}
An easy question to ask your friends/relatives/acquaintances/people you meet is, who do you think might be interesting for me to talk to about ____?  And you can fill in the blank with industries, job types, topics you find interesting. 

Your former students can sometimes be fascinating informaitonal interviews.
What are you up to these days? How did you get into that? What do you love about your work? 

I know someone who did a cold email to someone whose magazine article she found interesting. That person became a close friend and colleague. 

> If you would be interested in talking to them for fifteen minutes at a party, you can ask them to do an informational interview. 

### Myth #5 - Informational interviews have to be in person. {-} 

>We live in the information age. USE TECHNOLOGY.

If someone is down the street and their time is tight, a video conversation for 20 minutes may be all they're available for. Take it. 
Do interviews with people who are not in our geographic region even if you don't want to move. They may know about remote work opportunities or other kinds of work that you might appreciate. Or they might just have information that lets you write the perfect cover letter.  

### Myth #6 - Informational interviews are only for extroverts {-}
Setting aside my thoughts about introversion or extroversion and what it really means, I think this myth is pervasive in that a lot of people who are shy or who don't like crowds or strangers can struggle with.

You can always ask questions. People like other people who ask questions and listen. 

If you are good at listening and letting other people talk, you will do FINE at informational interviewing. Just let people talk.

### Tips for Informational Interviewing {-} 

- DO not ask for a job. Do not ask for a job. DO NOT ask for a job. 
It makes it awkward, and they probably don't have a job for you. 
Even if they do have a job for you, it's probably not their decision.
- Let THEM encourage you to apply for a job. 
- Schedule for no more than 30 minutes. 
- Give them a conversational out if they need to get back to work after 25 minutes. Let THEM tell you if they want to spend more time with you. 
Have an elevator speech about who you are, but be thoughtful about how you say things. 
- Temper your negative language and be conscious of how you tell your story. Consider talking about yourself in positive ways instead of negative ways. For instance:

>"I taught at the university for a few years but now I'm looking to pivot to nonprofit work/industry." instead of "Being an adjunct is horrible so I said to hell with them, I want to work somewhere else"* 

- Work to put things in language they might understand instead of the technical jargon of your field. 
>"I'm a social scientist with an interest in technology, science and sustainability" instead of "I'm an organizational sociologist whose research focused on sector differences among ecological standard setting organizations."

- It's ok to not know what you're going to do next. Most people who are outside of academia don't know what they're going to do next. Just be careful that you're not too negative about it. 

>Replace "I don't know what I'm doing" with "I'm curious about____" or "I'd like to know more about ______."     

- Look for places you can be of use to them: "I read this article you might find interesting. " or "I know someone in ___ field who is doing that kind of work." "Someone in my mentorship program was talking about the research she did on that topic." 
- Follow up follow up follow up!!! Follow them on social media. Send them an email with a thank you and any links/contacts you might have asked them for.
> Script: "Thanks so much for meeting with me, I really appreciated your thoughts about the future of your industry. I mentioned that article on beekeepers in New Zealand, here's the link to it."  

- Remind them in the follow up email if there were any connections they offered to you: 
>"I would really appreciate it if you were to connect me to Jane Doe at Incredible Corporation, she sounds like a fascinating person and I'd love to talk with her about her work making the world a better place"
"If any other ideas for people who I might chat with come to mind, please let me know."

- Rinse repeat. 
        
## Questions to ask in an informational interview? {-} 

- Tell me how you got into doing this work. 
- What is your job like? What do you love about it? What is challenging? 
- What are the big challenges/pain points right now in [industry]? 
- What do you think the upcoming trends are in your field/industry? 
- What conferences are really worth going to in your field? Why did you like them? 
- Who should I be reading? Who can help me learn more about this field or industry? 
- I really love doing [skill], but I'm trying to figure out where I might be able to do that kind of work. What thoughts do you have? 
- What does your typical day (or week) look like?
- What qualities or specific skills/proficiencies do you look for in a job candidate? 
- What are the growth areas in your industry? 
- What are the biggest challenges in your field/sector/job/company?
- What led you to this work? (a variation on how did you find this work/job?)
- Who else do you think I should talk to?
- How might I start in this field?
- What do you see yourself doing in 5 years? 
 

## Resources {-}

- [Taking the Work out of Networking](https://www.amazon.com/Taking-Work-Out-Networking-Connections-ebook/dp/B07CL5ZWL9/ref=sr_1_1?crid=YF7A057RL2MN&keywords=take+the+work+out+of+networking&qid=1581022058&s=books&sprefix=take+the+wor%2Ctoys-and-games%2C285&sr=1-1)
- [Succeeding Outside the Academy](https://kansaspress.ku.edu/978-0-7006-2688-5.html) - Edited volume with a chapter by Abby Bajuniemi 
- [Networking Strategies for Beginners](https://code.likeagirl.io/networking-strategies-for-beginners-986fe0b3efdf) 
- [Discover your Ideal Post Academic Career Using Informational Interviews](http://resources.careerpathwritingsolutions.com/2018/03/01/conduct-informational-interviews-to-create-your-ideal-career-path-off-the-tenure-track/) - Career Path
- [Spinning your Postac Web](https://theprofessorisin.com/2014/04/29/spinning-your-postac-web-networking-101/) - The Professor is In
- [Three Steps to a Perfect  Informational Interview](https://www.themuse.com/advice/3-steps-to-a-perfect-informational-interview) - The Muse
- You might also consider that mentoring relationships aren't one way [Business Mentorship](https://www.huffpost.com/entry/business-mentors_b_1925501?guccounter=1&guce_referrer=aHR0cHM6Ly93d3cuZ29vZ2xlLmNvbS8&guce_referrer_sig=AQAAAMiQJUkgDv2LueiDaqOb2yF13txE3_hjE8zdcTUGNiP_flM_rSNDGVTxxwG8iG7K9pz9fxwxvfiyBIMPxNdOHLWWdHSNdlJ0S9H-8ZA_6EpzUMgKj8dD3DEFz7pHlbnKv3bRGbMx5vSU3KdFifO7wX1zVlaqX_c7grIsRvqjaDit)
