---
title: "06-Identity"
output: html_document
---

# Changing Identities {-}

- Who are you outside of the academy? 
- How do we respond to the question "What do you do?" when we don't know?
- What if I'm overqualified?

## Identity and Post Academics {-}
When I researched and wrote the white paper [What I Wish I had Known](https://static1.squarespace.com/static/5a0cc397f09ca473053aea14/t/5aa700b071c10baf62f8ea88/1520894128791/What+I+Wish+I+Had+KnownFINAL.pdf) one of the key findings was around identity and emotions. I want to share part of that section of the paper with you here in hopes it can be the starting point for our discussion today. 

All of the quotes are from people who have left academia and who are answering what they wish they had known when they were leaving the academy. 

Many respondents described leaving academia as emotionally fraught. Some felt as if they were not only leaving their career and trying to find a new livelihood but also abandoning their identity along with it.

>“I wish I had known how long the transition would take, and how high the emotional toll would be. I lost a major part of my identity, though now I am learning that many of the things that made me love academia—it satisfied my unrelenting curiosity, allowed me to work through ideas in long-term projects, helped me constantly raise new questions—are still part of my life and work. I am now trying to find new ways to define myself, and it is frightening but also exciting.”

>“Your self-concept has to change, and that is a huge undertaking. It will take time. Be gentle with yourself, be hopeful and optimistic, and find a support network to keep you going when it's hard. Don't settle for a life that's less than you want. There's a whole world out there.”

>“DO IT!!! It's so much better out here. But be prepared to totally overhaul your beliefs and values and dreams too.”

>*“Your whole identity will change.”

Respondents wished they had known they would face emotions like anger, sadness, shame, loss, and grief. They said that those emotions lingered throughout the process of leaving and even beyond the transition.

>“You're not worthless, and neither is your degree. Academia is great at convincing us we have no value. If you can get yourself to a place where you see the value in yourself and your abilities/education beyond academia, you'll start seeing possibilities again. And that's a really hopeful, abundant feeling.”

>“The tremendous sense of loss and grief and anger that I'd feel. How lost I would feel, for years. And that it's relatively common for post-acs to experience this.”

>“How angry and betrayed I would feel.”
 
The transition took longer than respondents expected. They described the shift being more than just “adjusting to a new job” and said that they needed to look at the change in terms of years rather than months.

>“Also, don't think this will be a quick transition. So many people told me it takes 3 to 6 months to adjust to a new job, but none of those people understood that a transfer out of academia is far different from switching jobs. Anticipate the adjustment taking no less than a year, but likely several more.”

>“Prepare for the transition, read others’ stories, know that it may take 3 years before you feel ‘normal’ again.”

Some also described finding a “new narrative”  to understand or explain their story and indicate that this changed the way they thought about their career and their work.

>“Bridging occasional academic work and journalism can be quite challenging because they're such major mindset shifts. More than I anticipated. While I enjoy consulting from time to time and teaching a class here and there, I find I no longer have patience for the way that academia sucks you in, demanding such intensely deep but narrow attention. Part of what I love about freelancing is I get to learn about a lot of things while constantly working on my skills as a writer and interviewer. I'm sometimes not sure if doing both is sustainable for me long-term.” 

>“The biggest ‘aha!’ I've had since leaving the academy and starting a business is that, whether the business succeeds or fails, I have changed my narrative. Any interview I walk into after this, I walk into as an entrepreneur—it's my choice to talk about my academic background or not.”

Respondents discussed needing to find ways to express their own worthiness and the value of their degree. Some found ways to see their choice as valuable even as the academy may have deemed them not worthy.

>“I think that what is important is not to pin your self-worth on academic accomplishments. I tell my students, don't wait to ‘start your life’ when you graduate, because it will always be different versions of the same. Live now the way you want to live.” 

>“You will likely have a greater sense of self worth and that your intellect matters on the outside and just bc u leave academia doesn’t mean you don’t use those skills or write etc.”

>“Self care is not a luxury. And from what I witnessed, politics (and male-bonding over golf) usually have more to do with professional success than actual performance and accomplishment, so don't judge your own merit solely on rewards you may or may not have received.”

>“You are so much more valuable than the academy deems you. Get out and do things in the world!” 


## Four Metaphors Exercise  {-}
I've heard four main metaphors folks who have left academia have used to describe their relationship with the academy. 

These are very strong metaphors, so please know that **I am not saying that academia is or was these things**. Particularly if you have experienced one or more of these in reality, you may find the comparison jarring or inappropriate.  

I am simply pointing out that others who have been through this process have used these metaphors to describe their time leaving academia. I offer them as a way to grapple with and investigate your own experience. If the metaphor does not serve you, please set it aside. 

The questions below are designed to help you think through how these metaphors might relate. Want more questions? [I wrote up more on these metaphors here.](https://docs.google.com/document/d/e/2PACX-1vS0rq_KeoH286ALLQhNrZH5fp8mAlRTPEgN6vvb6_da-p-SUcimYf3xVsIYoTzFk4V_u7leA5pfkZmN/pub0)

### Academia as: {-}

*A Romantic Relationship* 
- Was it an unrequited love, a deep attraction or an abusive or indifferent partner? 
- Was the ending a divorce, a tentative separation or a breakup? 

*An Addiction* 
- Where did you feel a high from your academic work or life? When did you feel low? 
- When did you feel powerless in the academic life you lived?

*A Cult*
- What false beliefs did you internalize as a part of being in academic settings? 
- What was secret or exclusive about academia?

*An Ivory Tower* 
- Where were you isolated or kept apart from the rest of the world?
- What was esoteric or hard to explain about your academic career? 


  
